name: nwb_datajoint
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab>=3.*
  - nodejs=12.4.*
  - pydotplus>=2.0.*
  - dask>=2.30
  - pip>=20.2.*
  - pip:
    - labbox-ephys>=0.5
    - labbox-ephys-widgets-jp>=0.1
    - kachery
    - mountainsort4
    - ml_ms4alg
    - spikeinterface>=0.12
    - pynwb>=1.4,<2
    - hdmf>=2.5.1,<3
    - datajoint>=0.13.*
    - ghostipy
    - pymysql>=1.0.*
    - h5py==2.10.*
    - git+git://github.com/LorenFrankLab/ndx-franklab-novela
