name: nwb_datajoint
channels:
- defaults
- conda-forge
- edeno
- franklab
- novelakrk
dependencies:
- "python==3.8"
- matplotlib
- pandas
- networkx
- datajoint
- python-dateutil
- ipywidgets
- ipykernel
- nodejs
- jupyter
- jupyterlab
- nb_conda
- tqdm
- setuptools
- pytest
- pytest-cov
- coveralls
- pynwb>=1.4
- pybind11
- distributed
- pip
- pip:
  - ghostipy
  - spikeinterface
  - kachery==0.6.4
  - ml_ms4alg
