# FIRST: INSTALL CORRECT DRIVER for GPU, see https://stackoverflow.com/questions/30820513/what-is-the-correct-version-of-cuda-for-my-nvidia-driver/30820690
#
# install: conda env create -f environment_position.yaml
# update:  conda env update -f environment_position.yaml
# after installing do the following:
# conda activate spyglass-position
# conda env config vars set LD_LIBRARY_PATH=~/path/to/anaconda3/envs/spyglass-position/lib/
# run mamba install -c conda-forge wxpython
# run mamba install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge
# cd into spyglass and run pip install -e .
name: spyglass-position
channels:
  - conda-forge
  - defaults
  - pytorch
  - franklab
  - edeno
dependencies:
  - python>=3.8, <3.10
  - jupyterlab>=3.*
  - pydotplus>=2.0.*
  - libgcc
  - dask>=2.30
  - pip>=20.2.*
  - ipython
  - jupyter
  - position_tools
  - track_linearization
  - replay_trajectory_classification
  - ripple_detection
  - trajectory_analysis_tools
  - matplotlib
  - seaborn
  - skan
  - bottleneck
  - ipympl
  - tqdm
  - nb_conda
  - ffmpeg
  - pytorch<1.12.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.3
  - pip:
    - pubnub<6.4.0
    - mountainsort4
    - spikeinterface>0.90,<0.94.1
    - pynwb>=2.0.0,<3
    - hdmf>=3.1.1,<=3.2.1
    - datajoint>=0.13.6
    - ghostipy
    - pymysql>=1.0.*
    - sortingview>=0.8
    - git+https://github.com/LorenFrankLab/ndx-franklab-novela.git
    - pyyaml
    - click
    - "deeplabcut"
