name: nwb_datajoint
channels:
  - conda-forge
  - defaults
  - franklab
dependencies:
  - python=3.8
  - jupyterlab>=3.*
  - pydotplus>=2.0.*
  - dask>=2.30
  - pip>=20.2.*
  - position_tools
  - track_linearization
  - skan
  - bottleneck
  - ipympl
  - tqdm
  - nb_conda
  - jinja2==3.0.2
  - pip:
    - kachery
    - kachery-client>=1.1.7
    - mountainsort4
    - spikeextractors
    - git+https://github.com/SpikeInterface/spikeinterface.git
    - pynwb>=2.0.0,<3
    - hdmf>=3.1.1,<4
    - datajoint>=0.13.*
    - ghostipy
    - pymysql>=1.0.*
    - h5py==2.10.*
    - sortingview>=0.7.3
    - git+https://github.com/LorenFrankLab/ndx-franklab-novela.git
    - pyyaml
    - click
